version: "2"

checks:
  argument-count:
    enabled: true
  boolean-parameter:
    enabled: true
  class-coupling:
    enabled: true
  cyclomatic-complexity:
    enabled: true
  duplication:
    enabled: true
  method-count:
    enabled: true
  nested-control-flow:
    enabled: true
  return-count:
    enabled: true
  similar-code:
    enabled: true

plugins:
  javac:
    enabled: true
  checkstyle:
    enabled: true
  pmd:
    enabled: true
    config:
      rulesets:
        - "java-basic"
        - "java-braces"
        - "java-clone"
        - "java-codesize"
        - "java-comments"
        - "java-controversial"
        - "java-design"
        - "java-empty"
        - "java-finalizers"
        - "java-imports"
        - "java-j2ee"
        - "java-javabeans"
        - "java-junit"
        - "java-logging-java"
        - "java-migrating"
        - "java-naming"
        - "java-optimizations"
        - "java-typeresolution"
        - "java-unnecessary"
        - "java-unusedcode"
  eslint:
    enabled: true
  duplication:
    enabled: true

exclude_patterns:
  - "**/build/**"
  - "**/out/**"
  - "**/target/**"
  - "**/node_modules/**"
  - "**/*.min.js"

include_patterns:
  - "**/*.java"
  - "**/*.xml"
  - "**/*.js"
  - "**/*.json"
  - "**/*.properties"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/test/**"
  - "**/tests/**"
